# Node.js — JavaScript runtime built on V8
# Installs via MSI to Program Files with PATH integration

id: node
name: Node.js
description: JavaScript runtime built on V8
homepage: https://nodejs.org
license: MIT

version: "22.14.0"
version_cmd: "node --version"
version_regex: "v(\\d+\\.\\d+\\.\\d+)"

installer:
  type: msi
  url: https://nodejs.org/dist/v22.14.0/node-v22.14.0-x64.msi
  sha256: "0000000000000000000000000000000000000000000000000000000000000000"
  size_bytes: 31000000
  msi:
    properties:
      INSTALLDIR: "${PROGRAMFILES}\\nodejs"

side_effects:
  path:
    add:
      - "${PROGRAMFILES}\\nodejs"
  env:
    set:
      NODE_ENV: ""

metadata:
  categories: ["runtime", "development"]
  tags: ["javascript", "typescript", "npm", "v8"]
  maintainer: "uas-core-team"
  updated: "2026-02-01"

requirements:
  os: "10.0.0"
  arch: x64
  admin: true
  dependencies: []
